import {learningProgress} from "../routes/progress";
import type {DB} from "../db";import type {Rating} from "@lexiloop/shared";import {getCard} from "../db/cards";
/**
 * Ghi nhận một lượt ôn và tính lịch ôn tiếp theo theo thuật toán SM-2.
 * Again: học lại sau 10 phút; Hard/Good/Easy: tăng khoảng cách và điều chỉnh hệ số dễ.
 * Gửi lặp cùng `idempotencyKey` sẽ không bị tính hai lần.
 * @returns Thẻ sau khi cập nhật và cờ `duplicate`.
 */
export function review(db:DB,input:{cardId:number;rating:Rating;idempotencyKey:string;reviewedAt?:string;viewKey?:string}){return db.transaction(()=>{const existing:any=db.prepare("SELECT * FROM reviews WHERE idempotency_key=?").get(input.idempotencyKey);if(existing)return {duplicate:true,card:getCard(db,existing.card_id)};const card:any=db.prepare("SELECT * FROM cards WHERE id=?").get(input.cardId);if(!card)throw Object.assign(new Error("Card not found"),{status:404});let ease=card.ease_factor,reps=card.repetitions,interval=card.interval_days;if(input.rating==="again"){reps=0;interval=0;ease=Math.max(1.3,ease-.2)}else{reps++;if(input.rating==="hard"){interval=Math.max(1,Math.round(Math.max(1,interval)*1.2));ease=Math.max(1.3,ease-.15)}else if(input.rating==="good"){interval=reps===1?1:reps===2?6:Math.max(1,Math.round(interval*ease))}else{interval=reps===1?4:Math.max(4,Math.round(interval*ease*1.3));ease+=.15}}const at=new Date(input.reviewedAt||Date.now());const due=new Date(at);if(input.rating==="again")due.setMinutes(due.getMinutes()+10);else due.setUTCDate(due.getUTCDate()+interval);const status=input.rating==="again"?"learning":reps>=5?"mastered":"review";db.prepare("UPDATE cards SET status=?,ease_factor=?,interval_days=?,repetitions=?,due_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(status,ease,interval,reps,due.toISOString(),card.id);db.prepare("INSERT INTO reviews(card_id,rating,idempotency_key,previous_interval,next_interval,reviewed_at) VALUES (?,?,?,?,?,?)").run(card.id,input.rating,input.idempotencyKey,card.interval_days,interval,at.toISOString());db.prepare("INSERT OR IGNORE INTO study_views(card_id,source,event_key) VALUES (?,'flashcard',?)").run(card.id,input.viewKey??input.idempotencyKey);learningProgress(db);return {duplicate:false,card:getCard(db,card.id)};})();}
