import { duplicateGroups, removeDuplicates } from '../services/duplicates';
import {ensureDeck} from "./decks";
import {Router} from "express";import multer from "multer";import type {DB} from "../db";import {importCommitSchema,vocabularyInputSchema} from "@lexiloop/shared";import {dbStatus,inputParams,vocabularyRow} from "../services/frontend";import {commitRows,consumePreview,createPreview,exportBuffer,ImportError,MAX_IMPORT_BYTES,parseImportFile,parseWorkbook} from "../services/importExport";
/** Router `/api/vocabulary`: quản lý từ vựng, nhập/xuất file và xử lý từ trùng. */
export function vocabularyRouter(db:DB){const r=Router(),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:MAX_IMPORT_BYTES}});const save=db.prepare(`INSERT INTO cards(word,meaning,example,pronunciation,part_of_speech,topic,image_url,audio_url,tags,synonyms,tag,status) VALUES (@word,@meaning,@example,@pronunciation,@partOfSpeech,@topic,@imageUrl,@audioUrl,@tags,@synonyms,@tag,@status)`);/** Trả lỗi nhập file dưới dạng JSON thống nhất (mã lỗi, thông báo, chi tiết). */ const fail=(s:any,e:unknown)=>{if(e instanceof ImportError)return s.status(e.status).json({error:e.code,message:e.message,...(e.details===undefined?{}:{details:e.details})});if((e as any).code==="LIMIT_FILE_SIZE")return s.status(413).json({error:"FILE_TOO_LARGE",message:"File exceeds the 10 MB limit"});throw e};
  /** Liệt kê các nhóm từ trùng (cùng từ và nghĩa). */
  r.get("/duplicates",(_q,s)=>{s.json(duplicateGroups(db))});
  /** Xóa từ trùng, giữ lại bản được ôn gần nhất trong mỗi nhóm. */
  r.post("/duplicates/remove",(q,s)=>{if(!Array.isArray(q.body.groups)||q.body.groups.some((g:unknown)=>!Array.isArray(g)||g.some((id:unknown)=>!Number.isSafeInteger(id)))){s.status(400).json({message:"Invalid duplicate groups"});return}const result=removeDuplicates(db,q.body.groups);if(!result){s.status(409).json({message:"Vocabulary changed. Please check duplicates again."});return}s.json(result)});
  /** Xuất từ vựng ra CSV, XLSX hoặc JSON (có thể lọc theo deck). */
  r.get("/export",(q,s)=>{const format=String(q.query.format||"csv");const rows=q.query.deck?db.prepare("SELECT * FROM cards WHERE deck=? ORDER BY word").all(String(q.query.deck)):db.prepare("SELECT * FROM cards ORDER BY word").all();if(format==="json")return s.attachment("vocabulary.json").json(rows.map(vocabularyRow));const data=exportBuffer(rows,format==="xlsx"?"xlsx":"csv");s.type(format==="xlsx"?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"text/csv").attachment(`vocabulary.${format}`).send(data)});
  /** Đọc file CSV/XLSX/PDF và trả bản xem trước kèm lỗi để người dùng kiểm tra. */
  r.post("/import/preview",upload.single("file"),async(q,s,next)=>{try{if(!q.file)throw new ImportError(400,"FILE_REQUIRED","A multipart file field named 'file' is required");const parsed=await parseImportFile(q.file);s.json(createPreview(parsed.format,parsed.rows,parsed.errors,db))}catch(e){try{fail(s,e)}catch(x){next(x)}}});
  /** Xác nhận nhập các dòng đã xem trước (bỏ qua hoặc cập nhật từ trùng). */
  r.post("/import/commit",(q,s,next)=>{try{const input=importCommitSchema.parse(q.body);consumePreview(input.token,db);s.status(201).json(commitRows(db,input.rows,input.duplicateStrategy,input.deck))}catch(e){try{fail(s,e)}catch(x){next(x)}}});
  /** Nhập trực tiếp từ file CSV/XLSX (không qua bước xem trước). */
  r.post("/import",upload.single("file"),(q,s)=>{if(!q.file)return s.status(400).json({message:"File is required"});try{const parsed=parseWorkbook(q.file.buffer,q.file.originalname),strategy=q.body.duplicateStrategy||"skip";let imported=0,skipped=0;const errors:any[]=[];db.transaction(()=>parsed.forEach((x:any,i)=>{try{const existing=db.prepare("SELECT id FROM cards WHERE word=?").get(x.word);if(existing&&strategy==="skip"){skipped++;return}const tag=(x.tags||[])[0]||x.topic;if(existing){db.prepare("UPDATE cards SET meaning=?,example=?,pronunciation=?,part_of_speech=?,tag=?,synonyms=?,updated_at=CURRENT_TIMESTAMP WHERE word=?").run(x.meaning,x.example,x.pronunciation,x.partOfSpeech,tag,"[]",x.word)}else save.run(inputParams({...x,tag,synonyms:[]}));imported++}catch(e){errors.push({row:i+2,message:(e as Error).message})}}))();s.status(201).json({imported,skipped,errors})}catch(e){s.status(400).json({message:(e as Error).message})}});
  /** Liệt kê từ vựng có tìm kiếm, lọc (trạng thái, tag, deck), sắp xếp và phân trang. */
  r.get("/",(q,s)=>{const sortColumns:Record<string,string>={word:"cards.word COLLATE NOCASE",meaning:"cards.meaning COLLATE NOCASE",tag:"COALESCE(NULLIF(cards.tag,''),cards.topic) COLLATE NOCASE",status:"CASE cards.status WHEN 'new' THEN 0 WHEN 'learning' THEN 1 WHEN 'review' THEN 2 WHEN 'mastered' THEN 3 ELSE 4 END",reviewCount:"review_count"};const sort=typeof q.query.sort==="string"&&Object.hasOwn(sortColumns,q.query.sort)?sortColumns[q.query.sort]:sortColumns.word;const direction=q.query.direction==="desc"?"DESC":"ASC";const page=Math.max(1,Number(q.query.page)||1),pageSize=Math.min(200,Math.max(1,Number(q.query.pageSize)||20)),where:string[]=[],args:any[]=[];if(q.query.q){where.push("(word LIKE ? OR meaning LIKE ? OR example LIKE ?)");args.push(...Array(3).fill(`%${q.query.q}%`))}if(q.query.deck){where.push("deck=?");args.push(String(q.query.deck))}if(q.query.unassigned==="true"){where.push("deck IS NULL")}if(q.query.status){where.push("status=?");args.push(dbStatus(String(q.query.status)))}if(q.query.tag){where.push("tag LIKE ?");args.push(`%${q.query.tag}%`)}const w=where.length?`WHERE ${where.join(" AND ")}`:"",total=(db.prepare(`SELECT COUNT(*) n FROM cards ${w}`).get(...args) as any).n,data=db.prepare(`SELECT cards.*, COALESCE(review_totals.review_count,0) AS review_count FROM cards LEFT JOIN (SELECT card_id, COUNT(*) AS review_count FROM study_views GROUP BY card_id) review_totals ON review_totals.card_id=cards.id ${w} ORDER BY ${sort} ${direction}, cards.word COLLATE NOCASE ASC, cards.id ASC LIMIT ? OFFSET ?`).all(...args,pageSize,(page-1)*pageSize).map(vocabularyRow);s.json({data,page,pageSize,total})});/** Thêm từ vựng mới. */ r.post("/",(q,s)=>{const x=vocabularyInputSchema.parse(q.body),out=db.transaction(()=>{const deck=ensureDeck(db,x.deck);const out=save.run(inputParams(x));db.prepare("UPDATE cards SET deck=? WHERE id=?").run(deck,out.lastInsertRowid);return out})();s.status(201).json(vocabularyRow(db.prepare("SELECT * FROM cards WHERE id=?").get(out.lastInsertRowid)))});/** Cập nhật từ vựng. */ r.put("/:id",(q,s)=>{const x=vocabularyInputSchema.parse(q.body);if(!db.prepare("SELECT id FROM cards WHERE id=?").get(q.params.id))return s.status(404).json({message:"Không tìm thấy từ cần sửa."});const p=inputParams(x),out=db.transaction(()=>{const deck=ensureDeck(db,x.deck);return db.prepare(`UPDATE cards SET word=@word,meaning=@meaning,example=@example,pronunciation=@pronunciation,part_of_speech=@partOfSpeech,topic=@topic,image_url=@imageUrl,audio_url=@audioUrl,tags=@tags,synonyms=@synonyms,tag=@tag,status=@status,deck=@deck,updated_at=CURRENT_TIMESTAMP WHERE id=@id`).run({...p,deck,id:q.params.id})})();if(!out.changes)return s.status(404).json({message:"Vocabulary not found"});s.json(vocabularyRow(db.prepare("SELECT * FROM cards WHERE id=?").get(q.params.id)))});/** Xóa từ vựng. */ r.delete("/:id",(q,s)=>{const x=db.prepare("DELETE FROM cards WHERE id=?").run(q.params.id);s.status(x.changes?204:404).end()});return r;}
