import { useStudyView } from '../hooks/useStudyView';
import { playFeedback } from '../utils/feedbackAudio';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, CalendarClock, CheckCircle2, Dices, GraduationCap, Layers3 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../api/client';
import { Flashcard } from '../components/study/Flashcard';
import { Button, Card, Empty, PageHeader, Skeleton } from '../components/ui';
import type { Rating, StudyMode } from '../types';

const modes = [{id:'daily' as const,title:'Ôn tập hôm nay',desc:'Những từ đến hạn theo nhịp SRS của bạn.',icon:CalendarClock,color:'green'},{id:'new' as const,title:'Học từ mới',desc:'Mở rộng vốn từ theo giới hạn mỗi ngày.',icon:GraduationCap,color:'coral'},{id:'random' as const,title:'Trộn ngẫu nhiên',desc:'Một vòng tự do từ toàn bộ thư viện.',icon:Dices,color:'yellow'}];
const ratings: {id:Rating;label:string;hint:string;key:string}[]=[{id:'again',label:'Lại',hint:'10 phút',key:'1'},{id:'hard',label:'Khó',hint:'Ôn sớm hơn',key:'2'},{id:'good',label:'Tốt',hint:'Giãn lịch ôn',key:'3'},{id:'easy',label:'Dễ',hint:'Giãn xa hơn',key:'4'}];
/** Trang học flashcard với lịch ôn SRS (đến hạn, từ mới, ngẫu nhiên). */
export function StudyPage(){
 const queryClient=useQueryClient();
 const [mode,setMode]=useState<StudyMode>();const [index,setIndex]=useState(0);const [flipped,setFlipped]=useState(false);const [results,setResults]=useState<Rating[]>([]);
 const [deck,setDeck]=useState('');const decks=useQuery({queryKey:['decks'],queryFn:api.decks});
 const settings=useQuery({queryKey:['settings'],queryFn:api.settings});
 const summary=useQuery({queryKey:['study-summary',deck],queryFn:()=>api.studySummary(deck),refetchInterval:60000});
 const queue=useQuery({queryKey:['study',mode,deck],queryFn:()=>api.studyQueue(mode!,20,deck),enabled:!!mode,staleTime:0,refetchOnWindowFocus:false,refetchOnReconnect:false});
 useStudyView('flashcard', mode&&!queue.isFetching&&!queue.isError?queue.data?.sessionId:undefined, queue.data?.cards[index]?.id);
 const rate=useMutation({mutationFn:(rating:Rating)=>api.rate(queue.data!.cards[index].id,rating,queue.data?.sessionId),onSuccess:(_,rating)=>{void queryClient.invalidateQueries({queryKey:['vocabulary']});void queryClient.invalidateQueries({queryKey:['study-summary']});void queryClient.invalidateQueries({queryKey:['progress']});void queryClient.invalidateQueries({queryKey:['dashboard']});setResults(x=>[...x,rating]);setIndex(x=>x+1);setFlipped(false)}});
 /** Gửi đánh giá cho thẻ hiện tại (chỉ khi đã lật) và chuyển sang thẻ tiếp theo. */
 const choose=useCallback((rating:Rating)=>{if(mode&&queue.data?.cards[index]&&flipped&&!rate.isPending){playFeedback(rating==='good'||rating==='easy',settings.data?.soundEffects!==false,settings.data?.soundEffectsVolume);rate.mutate(rating)}},[mode,queue.data,index,flipped,rate,settings.data?.soundEffects,settings.data?.soundEffectsVolume]);
 useEffect(()=>{/** Phím tắt 1–4 để chọn Again/Hard/Good/Easy. */ const fn=(e:KeyboardEvent)=>{const item=ratings.find(x=>x.key===e.key);if(item)choose(item.id)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[choose]);
 if(!mode)return <div className="page study-landing"><PageHeader eyebrow="PHÒNG LUYỆN TẬP" title="Bạn muốn học thế nào?" body="Chọn một nhịp học phù hợp với năng lượng hôm nay."/><label style={{display: 'block', marginBottom: 20}}>Bộ flashcard<select className="input" value={deck} onChange={e=>setDeck(e.target.value)}><option value="">Tất cả các bộ</option>{decks.data?.map(item=><option key={item.name} value={item.name}>{item.name} ({item.count} từ)</option>)}</select></label><div className="mode-grid">{modes.map(({id,title,desc,icon:Icon,color})=><Card key={id} className={`mode-card mode-${color}`}><div className="mode-icon"><Icon size={27}/></div><h2>{title}</h2><p>{summary.data ? id==="daily" ? `${summary.data.dueCount} từ đến hạn cần ôn.` : id==="new" ? `${summary.data.newCount} từ chưa học.` : `${summary.data.total} từ trong bộ đã chọn.` : desc}</p><Button variant="ghost" onClick={()=>{setIndex(0);setResults([]);setFlipped(false);setMode(id)}}>Bắt đầu <ArrowRight size={16}/></Button></Card>)}</div><div className="study-tip"><Layers3 size={20}/><p><strong>Mẹo nhỏ:</strong> Đừng cố nhớ hoàn hảo. Trả lời trung thực giúp thuật toán xếp lịch tốt hơn.</p></div></div>;
 if(queue.isLoading)return <div className="study-session"><Skeleton className="flash-loading"/></div>;
 if(queue.error)return <div className="page"><Empty title="Không thể tạo phiên học" body="Máy chủ chưa phản hồi. Hãy quay lại sau."/><Button onClick={()=>setMode(undefined)}>Quay lại</Button></div>;
 const cards=queue.data?.cards??[];
 if(index>=cards.length)return <div className="page complete"><div className="complete-badge"><CheckCircle2 size={42}/></div><h1>{cards.length?'Hoàn thành phiên học!':'Hôm nay đã xong!'}</h1><p>{cards.length?`Bạn đã đi qua ${cards.length} thẻ. ${results.filter(x=>x==='good'||x==='easy').length} câu trả lời vững vàng.`:summary.data?.nextDue ? `Lần ôn tiếp theo: ${new Date(summary.data.nextDue).toLocaleString("vi-VN")}` : "Thêm từ mới vào bộ để bắt đầu học."}</p><div>{mode!=="new"&&!!summary.data?.newCount&&<Button onClick={()=>{setIndex(0);setResults([]);setFlipped(false);setMode("new")}}>Học từ mới ({summary.data.newCount})</Button>}<Button onClick={()=>{setMode(undefined);setIndex(0);setResults([]);setFlipped(false)}}>Chọn phiên khác</Button><Button variant="secondary" onClick={()=>{setIndex(0);setResults([]);setFlipped(false);queue.refetch()}}>Học lại</Button></div></div>;
 return <div className="study-session"><header className="session-head"><button onClick={()=>{setMode(undefined);setIndex(0)}}><ArrowLeft size={18}/> Thoát</button><div><span>{index+1} / {cards.length}</span><div><i style={{width:`${(index/cards.length)*100}%`}}/></div></div><span className="session-mode">{modes.find(x=>x.id===mode)?.title}</span></header><Flashcard key={cards[index].id} card={cards[index]} onFlip={setFlipped}/><div className={`rating-row ${flipped?'visible':''}`}>{ratings.map(r=><Button key={r.id} className={`rating rating-${r.id}`} onClick={()=>choose(r.id)} disabled={!flipped||rate.isPending}><kbd>{r.key}</kbd><span>{r.label}<small>{r.hint}</small></span></Button>)}</div>{rate.error&&<p role="alert">Chưa lưu được kết quả. Vui lòng thử đánh giá lại.</p>}{!flipped&&<p className="reveal-note">Lật thẻ để xem đáp án và tự đánh giá</p>}</div>;
}
